### ISSUE TITLE
Update README.md file for minnieTwitter android app

### ISSUE THREAD

**Issue by maheshrajus** [amino-os/Amino.Run-Demos#86]
minnieTwitter android app Readme.md file needs to be updated with the latest changes. 
Need to have clear steps on how to build and run the app from scratch.

**Comment by Vishwa4jeet** [comment]
This issue has been resolved via https://github.com/amino-os/Amino.Run-Demos/pull/94.

@maheshrajus Better use Fixes #Issue_Number, that way once your PR gets merged the issue referenced with it will also get closed.

Closing this issue now.
